<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scss.liquid</string>
		<string>css.scss.liquid</string>
	</array>
	<key>name</key>
	<string>SCSS (Liquid)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
				<string>source.css.scss</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.scss.liquid</string>
	<key>uuid</key>
	<string>f2a39460-98fd-11e1-a8b0-0800200c9a67</string>
</dict>
</plist>